### ISSUE TITLE
loading languages on-demand? (cljs)

### ISSUE THREAD

**Issue by daonsh** [taoensso/tempura#11]
When using Clojurescript, it seems that the dictionaries for all languages are always loaded from the server. This may be a burden for large dictionaries. Any tricks to make it load just the requested dictionary from the server?

Thanks for the library.

**Comment by ptaoussanis** [comment]
Hi Shauli,

This should be pretty easy to do - the dictionary format is just Clojure data. You can send the necessary dictionary subkeys (locales, etc.) to the client whenever it's convenient :-)

(I tend to use [Sente](https://github.com/ptaoussanis/sente) for this, but an Ajax request would also do).

Hope that helps?

**Comment by daonsh** [comment]
Thanks.
