### ISSUE TITLE
Is this recommended also without Reactjs?

### ISSUE THREAD

**Issue by daonsh** [taoensso/tempura#12]
Is there any use for this library for a web app with mostly static HTML where you need to just change the strings in the html to the right locale? Or another solution is recommended?

Obviously I could start looking for all the html tags and replace where necessary but that's cumbersome and slow...
(there's also some dynamic part, but it's smaller)

Thanks

**Comment by ptaoussanis** [comment]
Hi Shauli!

Yup, as the README mentions - should be a good fit for static HTML, Reactjs, even non-HTML stuff (e.g. console or backend applications).

Hope that helps, cheers :-)
