### ISSUE TITLE
Clean way to type multiline strings

### ISSUE THREAD

**Issue by Grahack** [taoensso/tempura#15]
Hi,
I could concatenate with `str` but is there a cleaner construct?

Thanks.

**Comment by ptaoussanis** [comment]
Hi there, I use https://github.com/ptaoussanis/encore/blob/d2e1e35dc9dcc9534c1a19ee40610428e07d3219/src/taoensso/encore.cljx#L2317 for the purpose and find it works well.

Hope that helps!
