### ISSUE TITLE
Documentation issues?

### ISSUE THREAD

**Issue by AndreaCrotti** [taoensso/tempura#16]
I was trying to use tempura (thanks for the it by the way) but I have some troubles getting any response out.
The first problem is that the example map is `(def my-tempura-dictionary` but then you are using

```
(tr ; Just a functional call
  {:dict example-dictionary} ; Opts map, see docstring for details
  [:en-GB :fr] ; Vector of descending-preference locales to search
  [:example/foo] ; Vector of descending-preference resource-ids to search
  ) ; => "foo"
```

But even fixing the name and trying other examples I always get `nil` for every call.
Second question is if it's actually support on Clojure or it's only clojurecript?
It looks like it should work on both but `tr` is not available when I try to require it in a Clojure repl.

Thanks a lot,
Andrea

PS. I can also try to contribute and propose some fixes myself if it helps

**Comment by ptaoussanis** [comment]
Hi Andrea,

> The first problem is that the example map is (def my-tempura-dictionary ...)

Thanks, that was a typo- fixing now.

> But even fixing the name and trying other examples I always get nil for every call.

Could you please be a bit more specific? What calls are returning nil? From the example, I have:

```clojure
  (def my-tempura-dictionary
    {:en-GB ; Locale
     {:missing ":en-GB missing text" ; Fallback for missing resources
    :example ; You can nest ids if you like
    {:greet "Good day %1!" ; Note Clojure fn-style %1 args
     }}

   :en ; A second locale
   {:missing ":en missing text"
    :example
    {:greet "Hello %1"
     :farewell "Goodbye %1"
     :foo "foo"
     :bar "bar"
     :bar-copy :en.example/bar ; Can alias entries
     :baz [:div "This is a **Hiccup** form"]

     ;; Can use arbitrary fns as resources
     :qux (fn [[arg1 arg2]] (str arg1 " and " arg2))}

    :example-copy :en/example ; Can alias entire subtrees

    }})

  (tr ; Just a functional call
    {:dict my-tempura-dictionary} ; Opts map, see docstring for details
    [:en-GB :fr] ; Vector of descending-preference locales to search
    [:example/foo] ; Vector of descending-preference resource-ids to search
    ) ; Returning "foo" as expected
```

> Second question is if it's actually support on Clojure or it's only clojurecript?

As per the README, there's Clojure and ClojureScript support.

> It looks like it should work on both but tr is not available when I try to require it in a Clojure repl.

Sorry, would require more details to help you debug. `tr` should be available in the `taoensso.tempura` namespace for both Clojure and ClojurScript.

Cheers! :-)

**Comment by miyamotosho** [comment]
Hi @ptaoussanis,

I've just bumped into a similar issue and found a way out, so I want to report it here.

First time trying tempura. Just added tempura 1.2.1 via clj-refactor. When I tried the code snippet from the doc, the tr function call just gave me `nil`. No errors so far. Found it weird and looked into cider-repl, where I found the clj-refactor having spat the following warnings:
```
WARN: com.taoensso/truss version 1.5.0 requested, but 1.3.4 already on classpath.
WARN: org.clojure/tools.reader version 1.2.1 requested, but 1.3.0-alpha3 already on classpath.
WARN: com.taoensso/encore version 2.94.0 requested, but 2.68.0 already on classpath.
WARN: org.clojure/clojure version 1.7.0 requested, but 1.9.0 already on classpath.
Loaded dependencies:
[[com.taoensso/tempura "1.2.1"]]
Dependencies not loaded due to conflict with previous jars :
[[com.taoensso/encore "2.94.0"]
 [com.taoensso/truss "1.5.0"]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/tools.reader "1.2.1"]]
```

Not exactly sure what to do, I ran `lein deps :tree` but no suggestion.

I switched to another project where I only require
```
[org.clojure/clojure "1.8.0"]
                 [hiccup "2.0.0-alpha1"]
                 [hickory "0.7.1"]
                 [clj-http "3.8.0"].
```
No luck here as well, but this time, requiring '[taoensso.tempura :as tempura] raised an error. Scratching my head, I ran lein deps :tree again. Here I saw silver lining: Leiningen spat a suggestion: 
```
[hickory "0.7.1"] -> [org.clojure/clojurescript "1.9.293"] -> [org.clojure/tools.reader "1.0.0-beta3"]
 overrides
[com.taoensso/tempura "1.2.1"] -> [com.taoensso/encore "2.94.0"] -> [org.clojure/tools.reader "1.2.1"]

Consider using these exclusions:
[com.taoensso/tempura "1.2.1" :exclusions [org.clojure/tools.reader]]
```
Following this suggestion and exluding `org.clojure/tools.reader` form `com.taoensso/tempura` solved the issue in this project as well as in my original project.

With little understanding of issues related to dependency conflicts, I cannot do anything other than just report what I've seen.
