### ISSUE TITLE
Selmer integration/tag?

### ISSUE THREAD

**Issue by Sgoettschkes** [taoensso/tempura#17]
I'm trying to add i18n to an existing app which was build with compojure and selmer as the templating engine. My current approach is to pass a (big) hashmap of variables to selmer representing the translated resources.

There would be two easier solutions:

1. Pass all resources to selmer by preparing a hashmap of all resources using the keys from the dictionary
2. Using a selmer tag which calls the tr function.

I believe 2 would be easier to understand and would translate well to places where html/variables need to be injected into the resource.

**Comment by brjann** [comment]
I have made two quick and dirty selmer tags for translation

    (parser/add-tag!
      :tr
      (fn [args context-map]
        (i18n/tr [(keyword (first args))]
                 (split (join " " (rest args)) #"[|]"))))

    (parser/add-tag!
      :trb
      (fn [args context-map content]
        (i18n/tr [(keyword (first args))]
                 (split (get-in content [:trb :content]) #"[|]")))
      :endtrb)

`i18n/tr` is an intermediate function that calls `tempura/tr`
`tr` is used as an inline tag with arguments within the tag (separated by |) while `trb` gets is arguments from its content (to allow for other tags to supply arguments; also separated by |)

Example usage in selmer template

`{%trb messages/sender %} {{sender-name}} | {{sender-title}} {%endtrb%}`

`{%tr messages/save-draft %}`

**Comment by ptaoussanis** [comment]
@brjann Thanks for this!
