### ISSUE TITLE
Capitalize words in some languages

### ISSUE THREAD

**Issue by brjann** [taoensso/tempura#19]
I would like to generate a string like "One day ago", "Two days ago" or "Three days ago". My translation map currently looks something like this

    {:days-ago     "%1 %2 ago"
     :1            "one"
     :2            "two"
     :3            "three"
     :day-singular "day"
     :day-plural   "days"}

The function to generate the string is not complicated, it selects day-word based on the number of days and capitalizes the first letter of the day-number. However, in Swedish the phrase would actually be "För två dagar sedan", or rougly "Since two days ago". The translation string would then be "För %1 %2 sedan". However, I don't want the "två" (two) to be capitalized anymore since it's not in the beginning of the sentence.

I can't figure out if this conditional capitalizing of a string can be easily accomplished using tempura. Any suggestions?

**Comment by ptaoussanis** [comment]
Hi there,

So Tempura intentionally doesn't try to tackle issues like this (which can be complex, and where a general ideal solution usually doesn't exist- only options with different tradeoffs).

Instead, it provides a framework of core common-case features necessary for translations- and tries to leave hooks/knobs for the parts where you'd want to integrate with other solutions for specific issues like capitalization, pluralizations, etc.).

In particular, note that dictionary resources can be arbitrary functions. That should give you the hook you need to plug in whatever logic you'd prefer here. But it'd be up to you either to code the logic, or call to another library which provides the logic you need.

Hope that helps / makes sense?

**Comment by brjann** [comment]
Yes, that makes sense. Also, when I re-read my example I realize that the solution is that the string generated by :days-ago should begin with a capital letter (it's not %1 or %2 that should be capitalized before they are given as arguments to :days-ago). It shouldn't be hard to somehow tag that string as beginning with a capital letter using hooks.
