### ISSUE TITLE
make parse-http-accept-header function public

### ISSUE THREAD

**Issue by yogthos** [taoensso/tempura#2]
It would be nice to be able to use `parse-http-accept-header` for writing custom middleware for Tempura.

**Comment by ptaoussanis** [comment]
Hey Dmitri, sure- PR welcome!

**Comment by yogthos** [comment]
Perfect

**Comment by yogthos** [comment]
Also, I like the commented version of the keys that are namespaced in the middleware. Since it'll be merged with other middleware, it avoids the chance of collision.

**Comment by ptaoussanis** [comment]
> Also, I like the commented version of the keys that are namespaced in the middleware.

Thanks for the input, had been on the fence about that. Modified in RC4.

**Comment by yogthos** [comment]
👍
