### ISSUE TITLE
Bug with fn-style-args only strings

### ISSUE THREAD

**Issue by DjebbZ** [taoensso/tempura#20]
Hello,

When a string to translate contains only a fn-style arg (`%1`), tempura returns the number 0 instead of the argument.

``` clojure
(tr {:dict {:en {:a "aaa"
                 :b "b %1"
                 :c "%1"}}}
    [:en]
    [:c]
    ["Tempura"])
=> 0
```

Bug occured inside my a app. I was able to reproduce it in my app and with a fresh clone of tempura, at tag `v1.1.2` in a `lein repl`.

_Note_: I know that it's a bit silly to have a text to translate where you just have nothing to translate. We happen to have a translation workflow when it can occur that not everything is translated (or translated properly) at one point.

**Comment by DjebbZ** [comment]
After some exploration, it seems that the function returned by `impl/str->vargs-fn` always returns 0 for the above mentioned strings:

``` clojure
((impl/str->vargs-fn "%1") ["toto"])
;; => 0

((impl/str->vargs-fn "hello %1") ["world"])
=> "hello world"
```

Hope this helps fixing the bug.

**Comment by ptaoussanis** [comment]
Hi Khalid,

Thanks for the clear error report (and for the follow-up)- that does indeed help with debugging. Will investigate and come back to you :+1:

**Comment by ptaoussanis** [comment]
Fixed with release of `[com.taoensso/tempura "1.2.0"]` 👍

**Comment by DjebbZ** [comment]
Happy to have helped !👍

Le dim. 11 mars 2018 à 14:02, Peter Taoussanis <notifications@github.com> a
écrit :
