### ISSUE TITLE
Positional parameters are not resolved in Reagent dict

### ISSUE THREAD

**Issue by field-theory** [taoensso/tempura#22]
Positional parameters can be used both in regular strings and in Reagent components. However, they are not working in option dictionaries of said components.

**Steps to reproduce:**
```clojure
(require '[taoensso.tempura :refer [tr]])
(tr {} [:en] [[:span "%1" [:a {:href "%3"} "%2"]]] ["Click here:" "link to localhost" "http://localhost"])
```

**Expected output:**
```clojure
[:span "Click here:" [:a {:href "http://localhost"} "link to localhost"]]
```

**Actual output:**
```clojure
[:span "Click here:" [:a {:href "%3"} "link to localhost"]]
```
The third positional parameter, `%3` is not replaced. If I write `[:href "%3"]` it works as expected. But with the link inside the dictionary it is not properly replaced.

**Comment by ptaoussanis** [comment]
Hi Wolfram, thanks for the short+clear report- that's very helpful + made it easy for me to reply quickly 👍 

IIRC, it had never occurred to me that someone might want to use positional parameters in attributes. Could you give me some idea what the use case is? I guess for something like `:alt` or `:title`?

**Comment by field-theory** [comment]
Thanks for your quick response and for your outstanding work on the tempura library!

My use case is to have a custom link embedded within a `span`. Basically, there is a (localized and language-dependent) lead text, a link text and a dynamically generated and (possibly) language-dependent link target.

Example:
1. `Why don't you reach out to [Adam]?`, where `[Adam]` links to Adam's page.
2. `Sprich doch mal mit [Adam Smith]`, where `[Adam Smith]` also links to Adam's page.

Of course, doing localized `:alt` and `:title` tags is another interesting, albeit different situation.

I might add that I have found a work-around: If I use a function
```clojure
(fn [[link-text url]] [:span "Why don't you reach out to " [:a {:href (str url)} (str link-text)] "?"])
```
for the localization then it works as advertised, i.e. `(tr {:dict [...]} [:en] key ["Adam" "http://localhost/adam"])` indeed works correctly.
(You do mention defining a function in your documentation, but maybe you could also show an example of how to actually invoke it?)

**Comment by ptaoussanis** [comment]
Great, thanks for the update. 

In principle I'm on board with adding support for args in attrs maps, think that would be a nice convenience with reasonable applications.

Would need to be something we can do without significantly affecting performance though. Should be possible, but I suspect it'd involve a non-trivial change.

Will try look at this if I have a free moment, otherwise also open to PRs in the meantime 👍

**Comment by ptaoussanis** [comment]
Just to follow up-

> (tr {} [:en] [[:span "%1" [:a {:href "%3"} "%2"]]] ["Click here:" "link to localhost" "http://localhost"])

Having had some more time to think about this, I'm wondering if the above couldn't maybe be a bit of an anti-pattern for the example you cited?

In the quoted code above, we're making the entire element (including :span, and :a tags) a part of the translation itself. If you have 10 language translations, each will have to reproduce the entire element. And in practice, this means that your translators may have to deal with some non-trivial Hiccup syntax.

Certainly doable, but I'm wondering if you'd considered instead doing something like the following:

```
[:span (tr ["Why don't you reach out to %1?"] [[:a {:href "bar"} (tr ["Adam"])]])] 
```

I.e. instead of having a single translation for the entire element, you have one translation for the :span - and one translation for the :a.

This focuses your translations more on text, and less on HTML structure.

Note (in case it wasn't clear) that it's perfectly acceptable for a `tr` call to accept other `tr` calls as arguments.

Does that make sense?

**Comment by field-theory** [comment]
Yes, that makes a lot of sense, actually!

It was indeed not clear to me that you could apply the `tr` macro recursively with the meaning "apply this translation using the current language".

Let me experiment a little bit with that ...

**Comment by field-theory** [comment]
Sorry, but I tried a couple of things now.

(1) Recursive invocation without passing context information:

    (def my-dict {:en {:missing "**MISSING**"
                       :links {:faq "http://faq.de/en" :mail "mailto:help-en@faq.de"}
                       :help {:faq "FAQ" :contact "Mail us" :faq-link [:a {:href (tr [:links/faq])} (tr [:help/faq])]}}})

The result was:

    CompilerException clojure.lang.ArityException: Wrong number of args (1) passed to: tempura/eval27163/tr--27164, compiling:(form-init1760131379493158406.clj:1:164)

So I cannot call `tr` recursively, at least not as easily as I thought.

(2) Injecting Hiccup via positional parameters

    (def my-dict {:en {:missing "**MISSING**"
                       :links {:faq "http://faq.de/en" :mail "mailto:help-en@faq.de"}
                       :help {:faq "FAQ %1" :contact "Mail us %1"}}})

When I use it the positional parameter is consumed as a string:

    (tr {:dict my-dict} [:en] [:help/faq] ["BLA"])
    (tr {:dict my-dict) [:en] [:help/faq] [:a {:href (tr {:dict my-dict} [:en] [:links/faq])}])

is converted to `"FAQ BLA"` and `"FAQ :a"`, respectively.

(3) Injecting Hiccup recursively, variant 2:

    (def my-dict {:en {:missing "**MISSING**"
                       :links {:faq "http://faq.de/en" :mail "mailto:help-en@faq.de"}
                       :help {:faq "FAQ" :contact "Mail us" :faq-link [:a {:href "%1"} "%2"]}}})

This yields for

    (tr {:dict my-dict} [:en] [:help/faq-link] [(tr {:dict my-dict} [:en] [:links/faq]) (tr {:dict my-dict} [:en] [:help/faq])])

the result

    [:a {:href "%1"} "FAQ"]

Using a function is definitely the best approach so far!

**Comment by field-theory** [comment]
Ok, after re-reading the docs I got your point at last!

I have now re-written the tutorial which explains the functionality of tempura in a little bit more verbose language. In particular, I focus on the most important things first and tried to make sure that code can be copy-pasted into the REPL.

Please have a look at the Pull Request and let me know if I missed anything.

**Comment by ptaoussanis** [comment]
> It was indeed not clear to me that you could apply the tr macro recursively with the meaning "apply this translation using the current language".

Just in case it's helpful, it sounds like it's possible you might be thinking this is more complicated than it is :-)

`tr` isn't a macro, just a regular function. It has either 3 or 4 arities:

```
(tr opts locales resource-ids) ; or
(tr opts locales resource-ids resource-args)
```

When provided, the `resource-args` are used for interpolation into "%" placeholders.

Assuming we ignore `opts` and `locales` for the moment-

```
(tr ["Hello world"]) ; => "Hello world"
(tr ["Hello %1"] ["world"]) ; => "Hello world", with "world" as an argument

But since the arguments (in `["world"]`) can be anything, they can also be other function calls- e.g.
(tr ["Hello %1"] [(tr ["world"])]) ; "Hello world", with "world" as the return value of `(tr ["world"])`
```

Hope that helps a little!
