### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [taoensso/tempura#24]
I want to design a logo for you. as a volunteer. If you have an idea, do not hesitate to say it. What are you saying ?

**Comment by ptaoussanis** [comment]
Hi @Batarian711,

Thanks a lot for reaching out - apologies for the delay replying!

Sure - if you're still interested in making a logo, I'd definitely be interested in seeing what you had in mind. I should caution two things though:

1. I probably won't be available to give much/timely input/feedback/etc.
2. I'm a little picky when it comes to logos, so wouldn't be able to promise that I'll use what you come up with.

And I'll note the combination could mean significant potential for frustration on your part :-)

Anyway, will leave it to you to decide if that still sounds interesting.

In any case, really appreciate you originally offering- thanks again :-)
