### ISSUE TITLE
make get-default-resource-compiler public

### ISSUE THREAD

**Issue by mt0erfztxt** [taoensso/tempura#26]
Good day.
I'm using version 1.2.1 of Tempura and after update to latest release of ClojureScript (version 1.10.439) it start to print warning `taoensso.tempura/get-default-resource-compiler is not public` on usage of [get-default-resource-compiler](https://github.com/ptaoussanis/tempura/blob/v1.2.1/src/taoensso/tempura.cljc#L30). Any chances for `get-default-resource-compiler` to be made public?

**Comment by ptaoussanis** [comment]
Done, thanks for the report! (And apologies for the slow response).
