### ISSUE TITLE
Tempura advanced compilation issues

### ISSUE THREAD

**Issue by amazing-Mantse** [taoensso/tempura#29]
After including Tempura in my project I get this error when compiling with figwheel : 
`Compile Warning   resources/public/js/taoensso/encore.cljs   line:2684  column:16

  Use of undeclared Var goog.structs/Map

  2679    (def ^:private coerce-xhr-params "Returns [<uri> <?data>]"
  2680      (let [url-encode
  2681            (fn url-encode
  2682              ([params]
  2683               (when (seq params)
  2684                 (-> params clj->js gstructs/Map. gquery-data/createFromMap .toString)))
                       ^---
  2685  
  2686              ([uri params]
  2687               (let [qstr (url-encode params)
  2688                     uri-with-query (if (str/blank? qstr) uri (str uri "?" qstr))]
  2689                 [uri-with-query nil])))`

**Comment by khellang** [comment]
This has already been fixed in encore v2.117.0 (https://github.com/ptaoussanis/encore/commit/af1dd287cd7bf7b35a389cd3026c9f1477d07631), but that dependency hasn't been updated in here (it's still at 2.94.0). Probably needs the same PR as this; https://github.com/ptaoussanis/timbre/pull/299.

**Comment by amazing-Mantse** [comment]
Hi,

Thank you for the update, but I am getting this error in the project
https://github.com/ptaoussanis/tempura not *encore*

**Comment by khellang** [comment]
> Compile Warning resources/public/js/taoensso/encore.cljs line:2684 column:16

👆 But your warning says "encore.cljs" 😉. As I mentioned, this library has a dependency on encore 2.94.0, while the fix is in 2.117.0 😄

**Comment by amazing-Mantse** [comment]
Ahh ... I see ... Sigh. So I can actually pull the code fix and do a pull request and hope they merge it?

**Comment by khellang** [comment]
> So I can actually pull the code fix and do a pull request and hope they merge it?

Yes, I think that would be best 👍

**Comment by ptaoussanis** [comment]
Thanks @khellang!

You can also just add `[com.taoensso/encore "2.117.0"]` to your dependencies (above/before Tempura) in the meantime. That'll force the newer version of that library, rather than the one bundled in Tempura.

**Comment by amazing-Mantse** [comment]
Ahh .. Ok, so now when I do an advanmced compilations I find my self with this error :

`WARNING: /matter/titan/source/titan-ui/out/taoensso/tempura/impl.js:96: WARNING - unreachable code
}catch (e20422){if((e20422 instanceof Error)){`

Is this where I need to write an extern for this?

**Comment by ptaoussanis** [comment]
No need for an extern, that warning can be safely ignored 👍

**Comment by bfontaine** [comment]
Isn’t there any way to fix this warning?

**Comment by ptaoussanis** [comment]
@bfontaine Not last time I checked, though haven't looked recently since it's not a high priority vs other tasks.
