### ISSUE TITLE
Use strings as keys (now it is only keyword)

### ISSUE THREAD

**Issue by kirillsalykin** [taoensso/tempura#30]

**Comment by ptaoussanis** [comment]
@kirillsalykin Hi Kirill, can you please provide some more context? I'm not sure what you're asking for here. Thanks!

**Comment by kirillsalykin** [comment]
it was a while :)
let me think what I meant...

probably it has something to do with 
```
(tr [:please-login "Please login here"])
```
I think it would be nice to accept string as a translation key, but it now see it is kinda tricky, because of this:
```(tr ["Please login here"]) ; Phase 2: works just like a text literal during dev```

**Comment by kirillsalykin** [comment]
Lemme close this one.
