### ISSUE TITLE
Wrong back-off for missing translations

### ISSUE THREAD

**Issue by lambda-ai** [taoensso/tempura#33]
Hi,

From the docs and from most usage, I expect missing resources for a language to result in back-off to the next element in the vector of resource ids, and if that's a string, to just use the string. That's useful behavior, because I'm porting a single-language project to a second language, and I prefer to have the original strings in the code to make the code more readable. So adding them to the original language in the dictionary seems overkill (and duplication). But (running this in a browser repl; tried both v1.4.0 and 1.5.0):

```
(tr {:dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
    [:en] 
    [:old-password "expect this"])
=> "expect this"
(tr {:dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
    [:en] 
    [:new-password "dont expect this"])
=> "bla"
(tr {:dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
    [:nl] 
    [:new-password "expect this"])
=> "bla"
```

Looks either like a bug that probably would have been noticed by others, or I'm not understanding the mechanism. I'm guessing the latter, but since it's such a basic example, I thought I'd file it as an issue.

**Comment by ptaoussanis** [comment]
@lambda-ai Hi there!

Just double checking whether you've seen the (recently-added) README example [here](https://github.com/ptaoussanis/tempura#10-second-example).

A slightly longer description of the mechanism can be found [here](https://github.com/ptaoussanis/tempura/issues/32#issuecomment-1122626100).

Do either of those help? If not, just ping and I'll investigate closer :-)

Cheers,

**Comment by lambda-ai** [comment]
Hi @ptaoussanis,
thank you for the quick reply. I looked at all the docs you pointed me to (and I read others before), but I still dont see why my example isn't a bug. It's the last of the three examples that's going wrong:

To me, it looks like the search is not limiting to only the listed languages (only :nl), and also scanning the :en resources. Note that doesn't happen in the first example, so it looks random to me.

I also ran the same in a normal clojure repl just now, but the same result as in the browser repl.

**Comment by ptaoussanis** [comment]
Hi @lambda-ai, you're welcome!

Ah, so it looks like the issue in your case is that by default `tr` options include `{:default-locale :en}`. If you remove the default locale, you'll get the behaviour I believe you were expecting:

```clojure
(tr {:default-locale nil
     :dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
  [:en]
  [:old-password "expect this"])
=> "expect this"

(tr {:default-locale nil
     :dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
  [:en] 
  [:new-password "dont expect this"])
=> "bla"

(tr {:default-locale nil
     :dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
  [:nl] 
  [:new-password "expect this"])

=> "expect this"
```

With the `{:default-locale :en}` option, your `[:nl]` locale vector actually looks like `[:nl :en]` - i.e.:

```clojure
(tr {:default-locale nil
     :dict {:en {:new-password "bla"}
            :nl {:old-password "meh"}}} 
  [:nl :en]
  [:new-password "expect this"])
"bla"
```

I hope that helps / makes sense?

**Comment by ptaoussanis** [comment]
This is unfortunately only mentioned in the docstrings atm, I'll create a new description of the full behaviour now and add it to the README.

**Comment by lambda-ai** [comment]
Hi @ptaoussanis ,
thanks, that makes sense! I didn't notice the default-locale functionality.
Thanks for all the hard work on your awesome libraries!

**Comment by ptaoussanis** [comment]
No worries, it's an easy mistake to make (and the default locale is easy to miss).

I've just added a new Wiki page with documentation [here](https://github.com/ptaoussanis/tempura/wiki). Hopefully this is helpful?

> Thanks for all the hard work on your awesome libraries!

You're very welcome, thanks for saying so!

Cheers :-)
