### ISSUE TITLE
Unable to use in re-frame project - Runtime resource loading not possible for cljs dictionarie

### ISSUE THREAD

**Issue by joe-crick** [taoensso/tempura#34]
Greetings! I just tried setting up Tempura for a new re-frame project I'm working on. All seemed well, until I rendered the page I'd added Tempura to:

> "Runtime resource loading not possible for cljs dictionaries. See `tempura/load-resource-at-compile-time` as an alternative."

I found nothing in the `readme` about how to load the resource at compile time---and nothing online. Can you shed any light on how I can load the dictionary at compile time?

**Comment by ptaoussanis** [comment]
@joe-crick Hi Joe,

If you're currently using `tempura/load-resource-at-runtime` directly, you should be able to just replace the call with `tempura/load-resource-at-compile-time`. You can check the docstring for this macro for more info.

If you're not using `load-resource-at-runtime` directly, then you likely have a `:__load-resource` key in your dictionary map? That won't work in Cljs, and would throw an error like the one you're seeing.

For use with Cljs, you either need to define a dictionary directly:

```clojure
(def my-dict {:en {:example "example"}}) ; etc.
```

or use `load-resource-at-compile-time`:

```clojure
(def my-dict (tempura/load-resource-at-compile-time "my-dict.edn")) ; etc.
```

Hope that helps?

**Comment by joe-crick** [comment]
@ptaoussanis That was super helpful. Thanks, Peter!
