### ISSUE TITLE
Extraneous :dict in tr's docstring

### ISSUE THREAD

**Issue by jindrichmynarz** [taoensso/tempura#4]
The docstring of `taoensso.tempura/tr` uses example options that contains extraneous [`:dict` key](https://github.com/ptaoussanis/tempura/blob/master/src/taoensso/tempura.cljc#L183), wrapping the options. If these example options are used, the dict is not found, and the `tr` function returns `nil`. The fix is to use an example options that have both `:dict` and `:default-language` as top-level keys.

Tested using 1.0.0-RC4.

**Comment by ptaoussanis** [comment]
Hi Jindřich, thanks for the catch- will fix now. Apologies for the delay replying!

Cheers :-)
