### ISSUE TITLE
:__load-resource does not work from uberjar

### ISSUE THREAD

**Issue by sveri** [taoensso/tempura#6]
Hi, 

I am using `:__load-resource` from the dictionary map like this

```clojure
(def local-dict
  {:de {:__load-resource "i18n/de.edn"}
   :en {:__load-resource "i18n/en.edn"}})
```

It works fine running in development mode from the REPL, but when I create an uberjar, the resources are not loaded. I assume it does not find the files if they are compiled into the jar (physically they are there, in the "i18n" folder.

**Comment by ptaoussanis** [comment]
Hi @sveri,

> I assume it does not find the files if they are compiled into the jar (physically they are there, in the "i18n" folder.

Have you confirmed that the i18n folder is actually being included in the jar? With Clojure+Leiningen, you'll normally want to put your i18n folder in `./resources` at the root of your project.

Hope that helps? Cheers! :-)

**Comment by sveri** [comment]
Hi @ptaoussanis, 

I confirmed that the folder is included in the jar, with the files.
You can checkout this commit: https://github.com/sveri/getless-clj/tree/08f02a63b0d90ef6b78588d1e4b303f93ff45ec3

and run `lein uberjar`. You will find the files inside the jar.
Then run it with `java -jar target/getless.jar`. Go to `localhost:3000` and you can see that the messages are missing. 

I was able to work around it by merging the dictionary with a function I wrote myself for loading resources:
https://github.com/sveri/getless-clj/blob/57fc40600dd77611acb92e5f7128636ae90e16ea/src/clj/de/sveri/getless/locale.clj

**Comment by ptaoussanis** [comment]
Hi there,

Sorry- don't have time to dig around into the project atm. Will say- shouldn't be any need for writing a special resource loader; Tempura will happily read from resource files bundled in a jar. (This is the most common way of deploying Clojure applications).

If it's not working as you'd expect, might be a Tempura syntax issue or a resource path issue. Would play around with those to try debug.

Otherwise happy to take a look at a minimum reproducible example if you're still having trouble and would like to get to the bottom :-)

Cheers!

**Comment by sveri** [comment]
Ok, I will dig into this and try to provide a minimal non working project.

**Comment by sveri** [comment]
I added a minimal example that shows the non working case: https://github.com/sveri/tempura-uberjar

**Comment by ptaoussanis** [comment]
Awesome, thanks for the minimal example - that was helpful! This was indeed a [bug](https://github.com/ptaoussanis/encore/commit/d5fb3c500f3e1faaa230e40e032fd39f28e6eb70) - appreciate the report.

Please fix by adding `[com.taoensso/encore "2.88.2"]` to your Lein dependencies before any other taoensso dependency.

Will update the dep on Tempura's next release.

**Comment by sveri** [comment]
Very nice, thanks for fixing that and thanks for all the nice libraries.
I am really positively surprised by your fast response :-)

**Comment by ptaoussanis** [comment]
No problem, thanks for saying so! Cheers :-)
