### ISSUE TITLE
Keywords with multiple slashes cause problems

### ISSUE THREAD

**Issue by opqdonut** [taoensso/tempura#8]
For instance when trying to use cloverage, clojure.tools.reader fails with `Invalid token: :foo/bar/quux`.

The clojure [reference] says

> '/' has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name, e.g. my-namespace/foo. '/' by itself names the division function.

and

> Keywords are like symbols

Which I interpret as saying keywords can only have one `/`.

How about using `.` or `-` to separate components? I can implement it if we can agree on a solution.

[reference]: https://clojure.org/reference/reader

**Comment by ptaoussanis** [comment]
Hi Joel,

Sorry, could you provide a little more context? Where are you seeing keywords with more than one slash?

**Comment by opqdonut** [comment]
If I have >2 levels in the dictionary, like

```
{:en
 {:component
  {:subcomponent
   {:text "text"}}}}
```

This corresponds to the translation key `:component/subcomponent/text`

**Comment by ptaoussanis** [comment]
> This corresponds to the translation key :component/subcomponent/text

Sorry if I'm missing something obvious, but what's leading you to that conclusion? Is there a bad example somewhere?

As you correctly noted, valid keywords can have at most a single slash. So in this case the correct translation key is `:component.subcomponent/text`.

Does that help?

**Comment by opqdonut** [comment]
Hmm weird, multiple slashes still work:

```
(tr {:dict {:en {:a {:b {:c "d"}}}}} [:en] [:a/b/c]) ;; ==> "d"
(tr {:dict {:en {:a {:b {:c "d"}}}}} [:en] [:a.b/c]) ;; ==> "d"
```

I'm not sure where I picked up the idea of multiple slashes. Perhaps the README could have an `:a.b/c` example for clarity?

**Comment by ptaoussanis** [comment]
> Hmm weird, multiple slashes still work:

Tempura happens to accept this particular bad input without any negative consequences, but the keyword is invalid and I'd strongly recommend not relying on this behaviour.

> I'm not sure where I picked up the idea of multiple slashes.

No problem :-)

> Perhaps the README could have an :a.b/c example for clarity?

Good idea, will do!

**Comment by opqdonut** [comment]
Thanks and sorry for bothering you :)

**Comment by ptaoussanis** [comment]
Zero problem :-) Cheers!

(Will keep this issue open to remind me to add an extra example to the README)

**Comment by ptaoussanis** [comment]
Haven't had much
