### ISSUE TITLE
Don't understand :missing-resource-fn

### ISSUE THREAD

**Issue by brjann** [taoensso/tempura#9]
I'm trying to use the :missing-resource-fn option to handle translation keys without a corresponding resource. But I can't get it to work. I would expect the following code to return "missing" but instead it returns nothing. Help much appreciated.

```clojure
(tr
  {:missing-resource-fn (fn [x] "missing")
   :dict {:en {
               :example {:x "Hello %1"
                         :z "Goodbye %1, it was nice to meet you!"}}}}
  [:en]
  [:example/y]
  ["Steve"])

**Comment by ptaoussanis** [comment]
Hi @brjann, you understand just fine - you've just discovered a silly bug :-) 

Thanks for the report, should be fixed with `[com.taoensso/tempura "1.1.2"]` (on Clojars now).

Cheers!

**Comment by brjann** [comment]
Awesome, thanks!

**Comment by ptaoussanis** [comment]
No problem, appreciate the report :-)
